/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */



#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
#include "scheduler.h"
#include "string.h"

Mutex_Reference Mutex1,Mutex2 ;
unsigned char payload[3] = {1,2,3} ;
unsigned char payload2[3] = {1,2,3} ;


Task_Reference Task1_Ref;
Task_Reference Task2_Ref,Task3_Ref,Task4_Ref;
uint8_t Task1Led,Task2Led,Task3Led,Task4Led;

void Task1(void){

	static int counter =0 ;
	while(1){
		Task1Led ^= 0x1;  /* Logic High */
		counter++;
		if(counter == 100)
		{
			MyRTOS_AcquierMutex(&Mutex1,&Task1_Ref);
			MyRTOS_ActivateTask(&Task2_Ref);
		}
		if(counter == 200)
		{
			counter = 0;
			MyRTOS_ReleaseMutex(&Mutex1);
		}
	}
}

void Task2(void){
	
	static int counter =0 ;
	while(1){
		Task2Led ^= 0x1;  /* Logic High */
		counter++;
		if(counter == 100)
		{
			MyRTOS_ActivateTask(&Task3_Ref);
		}
		if(counter == 200)
		{
			counter = 0;
			MyRTOS_TerminateTask(&Task2_Ref);
		}
		
		
	}

}

void Task3(void) {

	static int counter =0 ;
	while(1){
		Task3Led ^= 0x1;  /* Logic High */
		counter++;
		if(counter == 100)
		{
			MyRTOS_ActivateTask(&Task4_Ref);
		}
		if(counter == 200)
		{
			counter = 0;
			MyRTOS_TerminateTask(&Task3_Ref);
		}
   
	}

}

void Task4(void) {
	static int counter =0 ;
	while(1){
		Task4Led ^= 0x1;  /* Logic High */
		counter++;
		if(counter == 5)
		{
			MyRTOS_AcquierMutex(&Mutex1,&Task4_Ref);
		}
		if(counter == 200)
		{
			counter = 0;
			MyRTOS_ReleaseMutex(&Mutex1);
			MyRTOS_TerminateTask(&Task4_Ref);
		}
	}
}




int main(void)
{
	/* Init Hardware */
	HW_Init();

	MyRTOS_Init();

	Mutex1.Payload_Size = 3 ;
	Mutex1.p_Payload = payload ;
	strcpy ((char*)Mutex1.Mutex_Name, "Mutex1");

	Mutex2.Payload_Size = 3 ;
	Mutex2.p_Payload = payload2 ;
	strcpy ((char*)Mutex2.Mutex_Name, "Mutex2");


	Task1_Ref.Stack_Size = 1024;           /* Set Task1 Stack Size */
	Task1_Ref.Task_Priority = 4;           /* Set Task1 Priority */
	Task1_Ref.p_TaskEntry = Task1;         /* Set Task fucntion */
	strcpy((char*)Task1_Ref.Task_Name,"Task 1");  /* Set Task Name */


	Task2_Ref.Stack_Size = 1024;           /* Set Task1 Stack Size */
	Task2_Ref.Task_Priority = 3;           /* Set Task1 Priority */
	Task2_Ref.p_TaskEntry = Task2;         /* Set Task fucntion */
	strcpy((char*)Task2_Ref.Task_Name, "Task 2"); /* Set Task Name */


	Task3_Ref.Stack_Size = 1024;           /* Set Task1 Stack Size */
	Task3_Ref.Task_Priority = 2;           /* Set Task1 Priority */
	Task3_Ref.p_TaskEntry = Task3;         /* Set Task fucntion */
	strcpy((char*)Task3_Ref.Task_Name, "Task 3"); /* Set Task Name */

	Task4_Ref.Stack_Size = 1024;           /* Set Task1 Stack Size */
	Task4_Ref.Task_Priority = 1;           /* Set Task1 Priority */
	Task4_Ref.p_TaskEntry = Task4;         /* Set Task fucntion */
	strcpy((char*)Task4_Ref.Task_Name, "Task 4"); /* Set Task Name */


	MyRTOS_CreateTask(&Task1_Ref);
	MyRTOS_CreateTask(&Task2_Ref);
	MyRTOS_CreateTask(&Task3_Ref);
	MyRTOS_CreateTask(&Task4_Ref);

	MyRTOS_ActivateTask(&Task1_Ref);




	MyRTOS_startOS();



	while (1)
	{
	}


}
